version: "3.5"
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432"
  app:
    image: mitsumori/dev:2.4.6
    stdin_open: true
    tty: true
    env_file:
      - '.env'
    command: rails server -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
      - ~/bundle/alpine/2.4.6:/usr/local/bundle
      - /dev/shm:/dev/shm
    ports:
      - "3000:3000"
    depends_on:
      - postgres